### ISSUE TITLE
Deadlock detected

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/processor#35]
```python
vaindock_postgres_web    | ERROR:  deadlock detected
vaindock_postgres_web    | DETAIL:  Process 32 waits for ShareLock on transaction 4773; blocked by process 28.
vaindock_postgres_web    |      Process 28 waits for ShareLock on transaction 4777; blocked by process 32.
vaindock_postgres_web    |      Process 32: 
vaindock_postgres_web    |                  INSERT INTO player ("apiId", "name", "level", "xp", "played", "playedRanked", "playedCasual", "wins", "lifetimeGold", "streak", "lastMatchCreatedDate")
vaindock_postgres_web    |                  VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'epoch'::timestamp)
vaindock_postgres_web    |                  ON CONFLICT("apiId") DO UPDATE SET ("apiId", "name", "level", "xp", "played", "playedRanked", "playedCasual", "wins", "lifetimeGold", "streak") = ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
vaindock_postgres_web    |                  WHERE player.played < EXCLUDED.played
vaindock_postgres_web    |                  RETURNING "apiId"
vaindock_postgres_web    |              
vaindock_postgres_web    |      Process 28: 
vaindock_postgres_web    |                      UPDATE player SET "lastMatchCreatedDate"=$1
vaindock_postgres_web    |                      WHERE player."lastMatchCreatedDate" < $1
vaindock_postgres_web    |                  
vaindock_postgres_web    | HINT:  See server log for query details.
vaindock_postgres_web    | CONTEXT:  while locking tuple (0,30) in relation "player"
vaindock_postgres_web    | STATEMENT:  
vaindock_postgres_web    |                  INSERT INTO player ("apiId", "name", "level", "xp", "played", "playedRanked", "playedCasual", "wins", "lifetimeGold", "streak", "lastMatchCreatedDate")
vaindock_postgres_web    |                  VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'epoch'::timestamp)
vaindock_postgres_web    |                  ON CONFLICT("apiId") DO UPDATE SET ("apiId", "name", "level", "xp", "played", "playedRanked", "playedCasual", "wins", "lifetimeGold", "streak") = ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
vaindock_postgres_web    |                  WHERE player.played < EXCLUDED.played
vaindock_postgres_web    |                  RETURNING "apiId"
vaindock_postgres_web    |              
processor_1              | Task exception was never retrieved
processor_1              | future: <Task finished coro=<Worker.run() done, defined at /apps/api/api.py:164> exception=DeadlockDetectedError('deadlock detected',)>
processor_1              | Traceback (most recent call last):
processor_1              |   File "/apps/api/api.py", line 168, in run
processor_1              |     await self._work()
processor_1              |   File "/apps/api/api.py", line 161, in _work
processor_1              |     await self._execute_job(jobid, payload, priority)
processor_1              |   File "/apps/api/api.py", line 79, in _execute_job
processor_1              |     data["name"] == explicit_player)
processor_1              |   File "/apps/api/api.py", line 134, in _playerinto
processor_1              |     objid = await conn.fetchval(query, *data.values())
processor_1              |   File "/usr/local/lib/python3.6/site-packages/asyncpg/connection.py", line 289, in fetchval
processor_1              |     False, timeout)
processor_1              |   File "asyncpg/protocol/protocol.pyx", line 165, in bind_execute (asyncpg/protocol/protocol.c:55643)
processor_1              | asyncpg.exceptions.DeadlockDetectedError: deadlock detected
```

**Comment by schneefux** [comment]
Example with player A: A requests an update. The API is bugged and returns slightly different player data randomly (https://github.com/madglory/gamelocker-vainglory/issues/89).
In database: A has 200 wins and 1000 lifetimegold.
First 50 matches: A has 234 wins and 12345 lifetimegold.
Next 50 matches: A has 236 wins and 12390 lifetimegold.
Next 50 matches: A has 234 wins and 12345 lifetimegold.

Two processor threads pick up a match from job 1 and 2 simultaneously, work on it and try to upsert at the same time -> deadlock. I don't see a way to prevent it… The chance it happens will be lower once the data is processed in bigger batches, but I can't prevent it from happening. The only hope is that the API will be fixed.
